modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="MIT License https://github.com/BuiltBrokenModding/SBM-Growmeal/blob/1.16/LICENSE"
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Growmeal/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sbm-growmeal"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="sbmgrowmeal" #mandatory
version="1.0.2" #mandatory
displayName="Growmeal" #mandatory
description='''Instantly grow plants''' #mandatory

[[dependencies.sbmgrowmeal]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmgrowmeal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"