modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Growmeal/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-growmeal"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="sbmgrowmeal" #mandatory
version="1.0.0" #mandatory
displayName="[SBM] Growmeal" #mandatory
description='''Instantly grow plants''' #mandatory

[[dependencies.sbmgrowmeal]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmgrowmeal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"