modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Growmeal/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-growmeal"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="sbmgrowmeal" #mandatory
version="1.0.2" #mandatory
displayName="Growmeal" #mandatory
description='''Instantly grow plants''' #mandatory

[[dependencies.sbmgrowmeal]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmgrowmeal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"